[tool.poetry]
name = "wikiepediasearch"
version = "0.1.0"
description = ""
authors = ["aprishka <dennis@opryshko.com>"]


[tool.poetry.dependencies]
python = "^3.10"
wikipedia = "1.4.0"
fastapi = "*"
uvicorn = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
